// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package userrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetUserClient is the client API for GetUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetUserClient interface {
	//Get user by ID
	GetUser(ctx context.Context, in *FetchUserByIdRequest, opts ...grpc.CallOption) (*User, error)
	//Get users list by list of ids
	GetUserList(ctx context.Context, in *FetchUserListByIdRequest, opts ...grpc.CallOption) (*UsersList, error)
}

type getUserClient struct {
	cc grpc.ClientConnInterface
}

func NewGetUserClient(cc grpc.ClientConnInterface) GetUserClient {
	return &getUserClient{cc}
}

func (c *getUserClient) GetUser(ctx context.Context, in *FetchUserByIdRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/userrpc.GetUser/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getUserClient) GetUserList(ctx context.Context, in *FetchUserListByIdRequest, opts ...grpc.CallOption) (*UsersList, error) {
	out := new(UsersList)
	err := c.cc.Invoke(ctx, "/userrpc.GetUser/GetUserList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetUserServer is the server API for GetUser service.
// All implementations must embed UnimplementedGetUserServer
// for forward compatibility
type GetUserServer interface {
	//Get user by ID
	GetUser(context.Context, *FetchUserByIdRequest) (*User, error)
	//Get users list by list of ids
	GetUserList(context.Context, *FetchUserListByIdRequest) (*UsersList, error)
	mustEmbedUnimplementedGetUserServer()
}

// UnimplementedGetUserServer must be embedded to have forward compatible implementations.
type UnimplementedGetUserServer struct {
}

func (UnimplementedGetUserServer) GetUser(context.Context, *FetchUserByIdRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGetUserServer) GetUserList(context.Context, *FetchUserListByIdRequest) (*UsersList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserList not implemented")
}
func (UnimplementedGetUserServer) mustEmbedUnimplementedGetUserServer() {}

// UnsafeGetUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetUserServer will
// result in compilation errors.
type UnsafeGetUserServer interface {
	mustEmbedUnimplementedGetUserServer()
}

func RegisterGetUserServer(s grpc.ServiceRegistrar, srv GetUserServer) {
	s.RegisterService(&GetUser_ServiceDesc, srv)
}

func _GetUser_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userrpc.GetUser/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserServer).GetUser(ctx, req.(*FetchUserByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetUser_GetUserList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchUserListByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserServer).GetUserList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/userrpc.GetUser/GetUserList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserServer).GetUserList(ctx, req.(*FetchUserListByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetUser_ServiceDesc is the grpc.ServiceDesc for GetUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "userrpc.GetUser",
	HandlerType: (*GetUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUser",
			Handler:    _GetUser_GetUser_Handler,
		},
		{
			MethodName: "GetUserList",
			Handler:    _GetUser_GetUserList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userrpc/userrpc.proto",
}
